modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/JustEnoughProfessions/issues"
license="MIT"

[[mods]]
modId="justenoughprofessions"
version="${file.jarVersion}"
displayName="Just Enough Professions (JEP)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep"
authors="Mrbysco, ShyNieke"
description='''
Adds info about professions to JEI
'''

[[dependencies.justenoughprofessions]]
modId="jei"
mandatory=true
versionRange="[8.1.0.18,)"
ordering="NONE"
side="BOTH"
[[dependencies.justenoughprofessions]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"